baseURL: http://something-fresh.org/
languageCode: en-us
title: Hugo Fresh Theme
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/fresh.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Research Tool Flow
    # Hero subtitle (optional)
    subtitle: Optimize your research workflows
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Tools
    url: /tools
  - title: Categories
    sublinks:
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
  - title: Submit
    url: /submit
    button: true
  section2:
    title: Shared by the Community
    subtitle: and give back to the community
    features:
    - title: Everyone can contribute
      text: Submit your tools to .
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Discuss the usage of the tools
      text: Leave a comment when you feel like connecting
      icon: doc-sync
  section3:
    title: Be mindful
    subtitle:
    image: home/undraw_meditating_0nae.svg
    buttonText: Get started
    buttonLink: "#"
  section4:
  footer:
    # Logo (from /images/logos/___)
    logo: logo-banner-margin.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/kausalflow
      # Icons are from Font Awesome
      icon: github
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Browse
          link: /tools
        - text: Source
          link: https://github.com/kausalflow/tools
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
      column3:
        title: "Network"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
